### ISSUE TITLE
README里面的两个文档链接挂了

### ISSUE THREAD

**Issue by tkliuxing** [Dwarfartisan/goparsec#3]
> Paper Style
> http://bms.tratao.com/desktop/doc/0c3802e4ee404a71407f34996eff98ef
> Slide Style
> http://bms.tratao.com/slide/simple/0c3802e4ee404a71407f34996eff98ef##1

以上两个文档的链接挂了，BMS神马的，真的能用么？

**Comment by jnriver** [comment]
可以打开啊

**Comment by tkliuxing** [comment]
嗯，现在是好的。
